### ISSUE TITLE
Heh, so I can actually make comments on this thing

### ISSUE THREAD

**Issue by AxinAllCool** [b-alexis/codeup-web-exercises#1]
https://github.com/b-alexis/codeup-web-exercises/blob/2f19d45ebfd8bb35910c44c2c3bbc0f694f172b5/Welcome.html#L70

So....that last closing div on this file doesn't have an opening div. 

What does this mean you might wonder,  well I'll tell you.....

It means that my mentoree has failed you as a mentor, which also means that I have failed him. He should have caught this in a peer review, I taught him better than this. Missing this in his review brings me great dishonor and shame. You should be very disappointed in him over this review, to the extent that he might need to buy you something fancy to make up for it. I greatly apologize for this, and promise you that I'll work harder on making sure that he gets his shit together when it comes to reviewing code.

Axin

P.S. In reality some browsers will throw an error (look at the browser console), but the majority might just ignore the invalid closing div tag since it's at the end. If the tag was in the middle it might through off some of your page alignments.

**Comment by okcomputer** [comment]
I have failed you sensei pls forgive me.

**Comment by b-alexis** [comment]
Fixed.
Will punish mentor accordingly !
much learning, such wow!
